87 add backoffice deck
ESGI-69/challenge-node-vue pull request #112
Opened 2023-07-20 19:29 UTC by sguenier

2023-07-20 20:38 UTC, Timdev0 requested changes

2023-07-20 20:38 UTC, Timdev0 commented on backend/src/controllers/deck.js
> +    try {
ajouter une verif si c'est le bon user qui patch (j'ai fait ca pour le controller des payments)
```js
const deck = await deckService.findById(req.params.id);
if (deck.userId !== req.user.id) {
        throw new Error('Deck not found', { cause: 'Not Found' });
}
```

2023-07-20 20:38 UTC, Timdev0 commented on backend/src/controllers/deck.js
> +  delete: async (req, res, next) => {
ajouter aussi une verif si c'est le bon user qui delete

2023-07-20 20:40 UTC, mrpinkcat requested changes

2023-07-20 20:40 UTC, mrpinkcat commented on backend/src/controllers/deck.js
> +      if (!deck) return res.sendStatus(404);
```suggestion
      if (!deck) throw new Error('Deck not found', { cause: 'Not Found' });
```

Ca va automatiquement renvoyer une 404

https://github.com/ESGI-69/challenge-node-vue/blob/51392b282c6e93d101e2305b15aa72ec5e1b5ea7/backend/src/errorHandler.js#L56-L57

2023-07-20 20:40 UTC, mrpinkcat commented on backend/src/controllers/deck.js
> +      if (!deck) return res.sendStatus(404);
```suggestion
      if (!deck) throw new Error('Deck not found', { cause: 'Not Found' });
```

https://github.com/ESGI-69/challenge-node-vue/blob/51392b282c6e93d101e2305b15aa72ec5e1b5ea7/backend/src/errorHandler.js#L56-L57

2023-07-20 20:40 UTC, mrpinkcat commented on backend/src/controllers/deck.js
> +      res.json(updatedDeck);
```suggestion
      res.json(deck);
```

Tu peux pas faire ca la aussi ?

2023-07-20 20:40 UTC, mrpinkcat commented on backend/src/controllers/deck.js
> +      if (req.user.id !== deck.userId) return res.sendStatus(403);
```suggestion
      if (!deck) throw new Error('Deck not found', { cause: 'Not Found' });
      if (req.user.id !== deck.userId) throw new Error('This is not your deck', { cause: 'Unauthorized' });
```

Pas besoin de la 401, ta route est déjà protégé par le middleware

https://github.com/ESGI-69/challenge-node-vue/blob/51392b282c6e93d101e2305b15aa72ec5e1b5ea7/backend/src/middleware.js#L18-L20

Et pour les deux autres lignes, tu peux encore tout faire passer dans l'errorHandler.

https://github.com/ESGI-69/challenge-node-vue/blob/51392b282c6e93d101e2305b15aa72ec5e1b5ea7/backend/src/errorHandler.js#L56-L59

2023-07-20 20:40 UTC, mrpinkcat commented on backend/src/controllers/deck.js
> +      const user = await userService.findById(req.user.id);
```suggestion
```

Pas besoin de ca. Le user est déjà populate dans le middleware is logged

https://github.com/ESGI-69/challenge-node-vue/blob/51392b282c6e93d101e2305b15aa72ec5e1b5ea7/backend/src/middleware.js#L10-L19

2023-07-20 20:40 UTC, mrpinkcat commented on backend/src/controllers/deck.js
> +      if (!isOwned) return res.sendStatus(403);
```suggestion
      if (!await userService.hasCard(req.user, req.body.cardId)) throw new Error('You don't have this card', { cause: 'Unauthorized' });
```

Tu peux utiliser le `hasCard` dans le user service

https://github.com/ESGI-69/challenge-node-vue/blob/51392b282c6e93d101e2305b15aa72ec5e1b5ea7/backend/src/services/user.js#L73-L75

2023-07-20 20:40 UTC, mrpinkcat commented on backend/src/controllers/deck.js
> +      if (!req.user) return res.sendStatus(401);
```suggestion
```

Déjà check dans le middleware

2023-07-20 20:40 UTC, mrpinkcat commented on backend/src/controllers/deck.js
> +      if (req.user.id !== deck.userId) return res.sendStatus(403);
```suggestion
      if (!deck) throw new Error('Deck not found', { cause: 'Not Found' });
      if (req.user.id !== deck.userId) throw new Error('You don't own this deck', { cause: 'Unauthorized' });
```

https://github.com/ESGI-69/challenge-node-vue/blob/51392b282c6e93d101e2305b15aa72ec5e1b5ea7/backend/src/errorHandler.js#L56-L59

2023-07-20 20:40 UTC, mrpinkcat commented on backend/src/controllers/deck.js
> +      if (!isOwned) return res.sendStatus(403);
```suggestion
      if (!await userService.hasCard(req.user, req.body.cardId)) throw new Error('You don't have this card', { cause: 'Unauthorized' });
      if (!await deckService.hasCard(deck, req.body.cardId)) throw new Error('This card is not in this deck', { cause: 'Unauthorized' });
```

Utilise le `hasCard `du `userService`

https://github.com/ESGI-69/challenge-node-vue/blob/51392b282c6e93d101e2305b15aa72ec5e1b5ea7/backend/src/services/user.js#L73-L75

Tu peux aussi fais un `hasCard` dans le `deckService` et l'utiliser ici. Ca évite de supprimer une card qu'on a pas dans le deck.

2023-07-20 20:40 UTC, mrpinkcat commented on backend/src/controllers/user.js
> +      if (deck.userId !== req.user.id) { return res.sendStatus(403); }
```suggestion
      if (!deck) throw new Error('Deck not found', { cause: 'Not Found' });
      if (req.user.id !== deck.userId) throw new Error('You don't own this deck', { cause: 'Unauthorized' });
```

https://github.com/ESGI-69/challenge-node-vue/blob/51392b282c6e93d101e2305b15aa72ec5e1b5ea7/backend/src/errorHandler.js#L56-L59

2023-07-20 20:40 UTC, mrpinkcat commented on backend/src/controllers/user.js
> +      res.json(chooseFavDeck);
```suggestion
      const choosedFavDeck = await userService.chooseFavDeck(req.user, req.params.id);
      res.json(choosedFavDeck);
```

simple histoire de naming, histoire d'etre le plus précis possible sur le nom des variables

2023-07-20 20:40 UTC, mrpinkcat commented on backend/src/db/migrations/20230718195009-favorite-deck-association.cjs
> +        model: 'users',
```suggestion
        model: 'decks',
```

Peut etre que je me trompe, mais c'est pas une référence au deck ?

2023-07-20 20:40 UTC, mrpinkcat commented on backend/src/controllers/deck.js
> +        req.body,
Fait attention aux injections ici. Si le user trouve le nom d'une column de ta base, il peut injecter ce qu'il veut.
```suggestion
        {
          myColumn: body.myColumn,
        },
```

2023-07-20 20:40 UTC, mrpinkcat commented on backend/src/services/deck.js
> +    return cards;
```suggestion
    return deckModel.getCards({
      raw: true,
      nest: true,
    });
```

Pas besoin de retourner une variable ici

2023-07-20 20:40 UTC, mrpinkcat commented on backend/src/services/deck.js
> +    return removeCard;
```suggestion
    return  deckModel.removeCard(cardId);
```

pareil

2023-07-21 01:46 UTC, mrpinkcat commented on backend/package-lock.json
`git rm` le lockfile stp

2023-07-21 01:46 UTC, mrpinkcat commented on backend/src/controllers/deck.js
> +      if (req.user.id !== deck.userId) return res.sendStatus(403);
utilise le error handler, avec `throw`

2023-07-21 01:46 UTC, mrpinkcat commented on backend/src/controllers/deck.js
> +      if (req.user.id !== deck.userId) return res.sendStatus(403);
pareil

2023-07-21 01:48 UTC, mrpinkcat requested changes

2023-07-21 01:48 UTC, mrpinkcat commented on backend/package-lock.json
`git rm` le lockfile stv

2023-07-21 10:01 UTC, Timdev0 requested changes

2023-07-21 10:01 UTC, Timdev0 commented on backend/package-lock.json
non faut pas le suppr, ton lockfileVersion est en version 2 faut que tu passe sur une version plus récente de Node genre 18 ou 20, annule les changements de ce fichier https://stackoverflow.com/a/59756673/7687398
`git restore -s origin/main backend/package-lock.json `

2023-07-21 10:01 UTC, Timdev0 commented on frontend/package-lock.json
pareil que pour celui du backend

2023-07-21 18:03 UTC, Timdev0 approved these changes

2023-07-21 18:35 UTC, mrpinkcat approved these changes

2023-07-21 18:35 UTC, merged