10 add xp to user
ESGI-69/challenge-node-vue pull request #82
Opened 2023-07-06 21:36 UTC by ycenta

2023-07-07 11:23 UTC, Timdev0 requested changes

2023-07-07 11:23 UTC, Timdev0 commented on backend/src/db/migrations/20230705205448-user-add-xp.cjs
> +        allowNull: false,
mauvaise indentation install eslint sur ton IDE
et rebase sur main

2023-07-07 11:34 UTC, mrpinkcat commented on backend/src/db/migrations/20230705205448-user-add-xp.cjs
> +        allowNull: false,
Quand tu vas dans les extensions de vscode, y'a les extension recommandé pour ce workspace. Elle sont toutes dedans

2023-07-08 19:27 UTC, Timdev0 approved these changes

2023-07-08 19:27 UTC, merged